export { default as Twoweek } from "./Twoweek";
export { default as Home } from "./Home";
export { default as Alltime } from "./Alltime";
export { default as Multiplayer } from "./Multiplayer";
export { default as Links } from "./Links";
export { default as Singleplayer } from "./Singleplayer";
export { default as Viewnotfound } from "./Viewnotfound";
export { default as Bio } from "./Bio";
export { default as Contactus } from "./Contactus";
